game:
  folder_id: beta

url:
  web: https://giji.f5.si
  api: https://giji-api.duckdns.org/api
  firebase: https://giji-db923.firebaseapp.com
  assets:   https://giji-db923.firebaseapp.com
  style: ""
  # https://giji-db923.firebaseapp.com
  store: https://s3-ap-northeast-1.amazonaws.com/giji-assets
  sow:   https://s3-ap-northeast-1.amazonaws.com/giji-assets/sow

firebase:
  apiKey: "AIzaSyDIKOyZtB02BkMtEQt2dXVVqWYQOPNmiYo"
  authDomain: "giji-db923.firebaseapp.com"
  databaseURL: "https://giji-db923.firebaseio.com"
  projectId: "giji-db923"
  storageBucket: "giji-db923.appspot.com"
  messagingSenderId: "133620449014"

