project_id: giji-db923
type: service_account

client_id: 111848029046354217347
client_email: firebase-adminsdk-ezvri@giji-db923.iam.gserviceaccount.com

auth_uri: https://accounts.google.com/o/oauth2/auth
token_uri: https://oauth2.googleapis.com/token
auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-ezvri%40giji-db923.iam.gserviceaccount.com

private_key_id: 3bda5f2ad6fd84fbb5a56e7d18c6cd1f41aaee78
private_key: |-
  -----BEGIN PRIVATE KEY-----
  MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCm8QD6xDIXKPkY
  TPo69aevdNmFdpc/xpnLoOiEHOlMPE0nkDfHu7DEbA45ljPSI2XjFKUrez3U8F0e
  bCn6OgtPs4Ztb/wlYDcbS+GRm4i2zkjkGdeIE1Wh1Cxe+Py/OvhnFOLuEE/4/gEB
  22A0d0djb1orHp73eVJDDvTY/JkdVsfhVxZphF5BrklZ7iif2ioG68AK+dUv7ddU
  Y2KC4RvkgZuD+SinVIRq/ysrtHDm6zz20OqHw9D/d2Zg3fKSOmXrSBdcLFkvd8kB
  gmH7+z2DJPl6e/pXafP/GFXYhyxKKs91nD9onwhX6ExJFg79TOTwJWu1tdf3gma3
  orhioTyHAgMBAAECggEAAca8Cpmz1BNCM0P+avTaMpUSYMfWQX4iJ3cwLNex6SHA
  db9PGKJNSzRrIlRle22XqUbloFomBPIEdk0S/+/w1t7uJelJzDat323QmfVcYGA+
  3k54FfaUCVjHRWtuJQrCQeEzA512JwwXg/w1ldlUZSEg2ydEQcCEuOSb2QM3DdzY
  ypsMVYKsgNSvt+7Pvld+oMQWzy462ozAoN/Pe592kQva3z8O6arRuQ/LQ3PPn6a9
  QARohxGKdbt03c1vitgwZHWIrGWk1qpCNNAByO24SHgiEy/yc+C9IE/33oTWS3G2
  Pl+ZsQUpcYaVU9M3KkNb9P4dqGCa6ysnM/Hb3TBWgQKBgQDRiLSUcQ6qHZkdjUKO
  zW/i5nselQUB+deY0XA/rDXZlmedF31rRAXeDyYhjs9DKO58avu9RmOJ6zUOK2oA
  6KhlETLZv5Sz8jX4r3zMbs9qZMVcrRKnooTwuJnzoGhLXrIYl3BZewEtumtvqYDW
  SciDXNGTencP8wkuTaJRYYmM8QKBgQDL9k60q/mdUSr/B3VjENv4trFmAwkgQ3KR
  nbXRytGdKXrxDFNMilHPhOWlDk5EdK0f9mu83b2yiv1aMau9rJsYG/ISUVcRyo9S
  X+TQb36Xk7JhVbl8YIK/VzlMv3LFZ8xJMTI81BhMqD8eTxu19Ku0K0kU/bfxN5kl
  KnfoFo5A9wKBgGNYns324M4VpIBXdqRAkXkScHOqkipCrE8/lioKW6nj3xKjjYqr
  QODta9XjYS/lm1WQX/V5Bz7gL1KdkPAHX7gztFl7tWSwRZi4k8JWE6/NQapUQREM
  RF3iGNRjTK/XoTd5rgIvCPsGdWQHCRgQ+aoW+yMioIsGX2b91iUhytbxAoGAf44o
  psEuuH38n8XwWeY/S4ol46BeYrkLu5mgDfYDpYA9jOaiaanPhDKe09zggdteMjEQ
  K+uZKUHXNEMAHv0FecxwVZhdFZlSjLfAB8LSrsUFt+2+tNQ+sJ9CDIdmpaJGljeY
  LYaPM9G8t53NvLupbmHrsJ8EHG0i76Vhm9oPWP0CgYBnkVN9QqGTqTFAO6ytUrjY
  yY7vixVss8Yz6CslaDo3DoxbBDKwETLEvX6/wHVNyUymZGAmcEP+FVESLV3edvPx
  bUmT2a9Ss9w2kckd/y3roANBkXBeWf0nthuZ3F0hLOaFEQjiOUCYnoTosYDfUzpZ
  /p8d966SI1ZErPuxUMN26A==
  -----END PRIVATE KEY-----
